### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Shinzuu** [Shinzuu/QuickXS#9]
- [x] Home, Routine, Events, Links page
- [x] Home should show next day schedule + next 3 Events (both of them should show minimum info)
- [x] Routine is detailed routine
- [x] Events is detailed events
- [x] Links should keep all the reading materials + any academic links (like PUAIS)
- [x] Data in JSON format (server-less)

**Comment by Shinzuu** [comment]
done
